apiVersion: v1
kind: Secret
metadata:
  name: mongodb-backup-secrets
type: Opaque
data:
  mongodb-uri: {{ .Values.mongodb.uri | b64enc | quote }}
  ftp-server: {{ .Values.ftp.server | b64enc | quote }}
  ftp-username: {{ .Values.ftp.username | b64enc | quote }}
  ftp-password: {{ .Values.ftp.password | b64enc | quote }}
